project:
  type: website
  output-dir: docs

website:
  title: "DSPG2024_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bootingabend
      - icon: linkedin
        href: https://linkedin.comin/naomi-mauss-a0b112252/
format:
  html:
    theme: cosmo
    css: styles.css



